language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-svgr
    branch: publish
  api_key:
    secure: iK1fCCKHT72yI5QY4rTJASNuxPwMi/TWUXcOluCYlRItCjIe/GBe52427GB+NJIt39DPgdyxYsUKy/s9QLfS6hpfwSVEEUKzDKDrxlnwDLS4204hzy97Q1AzRo7vW1y6/aksdbLSDu7v0PQafFxXBtvEfeqYKoE5WhXRlgpCPjmr3XvGhePIGEvI0+ylO+lgnCSjiw7Jd4Tx5fYH7wi6/6e45iY83BXJQ2uAZn9cH0NZzNrGr6L6lSWWe5x+RJXExUHAJgGwp+4aK+hOFHCkgsuvuw9guC2ikVYZV2BAtIqe2K5tJy3x5eYaLL++G6FCQBgPD8yVy5GWLicag8nmNFImOwFhZnkvrEWIxAZWRxAQ9XGnupmesO0BFvBKPshICO8z2TdF1tXSBloS5ht0exiKMyMdUnI3RCpXgN4T8I5uUzL97vp8WSZp9XZdceHISGWXCw4yygorpIDqH5ktP+GyNlULl8rLkO4vGviGLecKXdlvH0Ok8cR2aqz+OoICgg/X05wdGh1H/gFo08t7NEVhwWOb8bqTTr5RWH5dGWn8dEstWgTPuOE6SxbjK8oGHunq8gGDtTxIlCj3wVCHU298vPdNoIf9iXF6i+wHL4XzRTOGiWZRx8jsT8J6BcTvBTu9KB+3LZQ312zCAmOLnXhpr/2aEy6GHzU2kSb2L3U=
